config/routes.rb
Rails.application.routes.draw do
  # root 'books#index' # URI is / or /books
  root "pages#home"
  resources :books
  resources :authors
  get "mybestread" => "mybestread#profile", as: :mybestread

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books

  def full_name
    first = read_attribute(:first_name)
    prefix = read_attribute(:prefix)
    last = read_attribute(:last_name)

    if prefix != ""
      full = "#{first} #{prefix} #{last}"
    else
      full = "#{first} #{last}"
    end
  end


  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :author_img, length: { maximum: 250 }, allow_blank: true
  validates :bio, length: { maximum: 10000 }
  validates :quotes, length: { maximum: 1000 }, allow_blank: true

end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :author

    validates :title, presence: true
    validates :title, uniqueness: true

    validates :year, length: { minimum: 4, maximum: 4}
    validates :cover_img, length: { maximum: 250 }, allow_blank: true
    validates :desc, length: { maximum: 10000}
    validates :pages, length: { maximum: 5}, allow_blank: true
    validates :isbn, length: { minimum: 10, maximum: 14}, allow_blank: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
# I don't understand why we can have an instance variable (@author) that changes with every other method. Wasn't the whole point of an instance variable that it would be accessable from outside the method (but inside the class?)

class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end

  def show
    @author = Author.find(params[:id])
  end

  def new
    @author = Author.new
  end

  def create
    author_params = params.require(:author).permit(:first_name, :prefix, :last_name, :author_img, :bio, :quotes)

    @author = Author.new(author_params)

    if @author.save
       redirect_to @author
    else
       render 'new'
    end
  end

# I don't understand why we have an edit method and an update method.
  def edit
    @author = Author.find(params[:id])
  end

  def update
    @author = Author.find(params[:id])
    author_params = params.require(:author).permit(:first_name, :prefix, :last_name, :author_img, :bio, :quotes)

    if @author.update_attributes(author_params)
      redirect_to @author
    else
      render 'edit'
    end
  end

  def destroy
    @author = Author.find(params[:id])
    @author.destroy
    redirect_to authors_path
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)

    if @book.save
       redirect_to @book
    else
       render 'new'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])

    if @book.update_attributes(book_params)
      redirect_to @book
    else
      render 'edit'
    end
  end

  def destroy
    @book = Book.find(params[:id])

    @book.destroy

    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :year, :cover_img, :desc, :pages, :isbn, :author_id)
  end
end

app/controllers/mybestread_controller.rb
class MybestreadController < ApplicationController
  
  def profile
    @readbooks = Book.last(4)
    @wishbooks = Book.first(2)
  end



end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @last_book = Book.last
    @last_author = Author.last
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/mybestread_helper.rb
module MybestreadHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/authors/_form.html.erb
<%= form_for @author do |f| %>

<ul class="error">
  <% @author.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>

  <%= f.label :first_name, class: "first_name" %>
  <%= f.text_field :first_name, class: "first_name" %>

  <%= f.label :prefix, class: "prefix" %>
  <%= f.text_field :prefix, class: "prefix" %>

  <%= f.label :last_name, class: "last_name" %>
  <%= f.text_field :last_name, class: "last_name" %>

  <%= f.label :author_img, class: "author_img" %>
  <%= f.text_field :author_img, class: "author_img" %>

  <%= f.label :bio, class: "bio" %>
  <%= f.text_area :bio, class: "bio" %>

  <%= f.label :quotes, class: "quotes" %>
  <%= f.text_area :quotes, class: "quotes" %>

  <%= f.submit (@author.new_record? ? "Create" : "Update") %>

<% end %>

app/views/authors/edit.html.erb
<article>
  <h1>Edit Author</h1>

  <%= render "form" %>
</article>

app/views/authors/index.html.erb
<article class="authors">
  <header>
    <h1>Authors</h1>
  </header>

  <ul>
    <% @authors.each do |author| %>
      <li><%= link_to "#{author.full_name}", author_path(author.id) %></li>
    <% end %>
  </ul>
</article>

<footer>
  <%= link_to "Add an author", "/authors/new", class: "button"%>
</footer>

app/views/authors/new.html.erb
<article>
  <h1>New Author</h1>

  <%= render "form" %>
</article>

app/views/authors/show.html.erb
<article class="author">
  <header>
    <%= image_tag @author.author_img %>
    <h1><%= @author.full_name %></h1>
  </header>

<main>
  <div>
    <h2>Biography</h2>
    <p><%= @author.bio %></p>

    <h3>Quote</h3>
    <quote><%= @author.quotes %></quote>

  </div>
</main>

<footer>
  <div>
      <h4>Books by <%= @author.full_name %></h4>
      <% if @author.books.any? %>
      <ul>
        <% @author.books.each do |book| %>
          <li><%= link_to book.title, book_path(book.id) %></li>
        <% end %>
      </ul>
    <% else %>
      <p>There were no books added, written by <%= @author.full_name %></p>
    <% end %>
    </div>
  </footer>
</article>

<footer>
  <%= link_to "Delete", author_path(@author.id), method: :delete, data: { confirm: "Are you sure?" } %>
  <%= link_to "Edit", edit_author_path(@author.id) %>
  <%= link_to "All Authors", "/authors" %>
</footer>

app/views/books/_form.html.erb
<%= form_for @book do |f| %>

  <ul class="error">
    <% @book.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>

  <%= f.label :title, "Book Title", class: "title" %>
  <%= f.text_field :title, class: "title" %>

  <%= f.label :author_id, "Author", class: "author" %>
  <%= f.collection_select(:author_id, Author.all, :id, :full_name) %>

  <%= f.label :year, class: "year" %>
  <%= f.number_field :year, class: "year" %>

  <%= f.label :cover_img, "Add Book Cover", class: "cover" %>
  <%= f.text_field :cover_img, class: "cover" %>

  <%= f.label :desc, "Description", class: "description" %>
  <%= f.text_area :desc, size: "60x30", class: "description" %>

  <%= f.label :pages, class: "pages" %>
  <%= f.number_field :pages, class: "pages" %>

  <%= f.label :isbn, "ISBN", class: "isbn" %>
  <%= f.text_field :isbn, class: "isbn" %>

  <%= f.submit (@book.new_record? ? "Create" : "Update")  %>
<% end %>

app/views/books/edit.html.erb
<article>
  <h1>Edit Book</h1>

  <%= render "form" %>
</article>

app/views/books/index.html.erb
<article>
    <h1>Books</h1>

  <main>
    <ul>
      <% @books.each do |book| %>
      <li>
        <%= link_to (image_tag book.cover_img, size: "180x268"), book_path(book.id) %>
        <!-- <%= image_tag book.cover_img, size: "90x134" %> -->
      </li>
      <% end %>
    </ul>
  </main>
</article>

<footer>
  <%= link_to "Add New Book", new_book_path, class: "button" %>
</footer>

app/views/books/new.html.erb
<article>
  <h1>Add New Book</h1>

  <%= render "form" %>
</article>

app/views/books/show.html.erb
<article class="book">
  <header>
    <h1><%= @book.title %></h1>
    <h2>by <%= link_to @book.author.full_name, author_path(@book.author.id) %></h2>
    <p> Year: <%= @book.year %></p>
  </header>
  <main>
    <%= image_tag @book.cover_img, { alt: "Cover Image of '#{@book.title}'", size: "270x402"}%>
    <section>
      <div class="description">
        <h4>Description</h4>
        <p><%= @book.desc %></p>
      </div>
      <div class="pages">
        <h4>Number of pages</h4>
        <p><%= @book.pages %></p>
      </div>
      <div class="isbn">
        <h4>ISBN</h4>
        <p><%= @book.isbn %></p>
      </div>
    </section>
  </main>
</article>
<footer>
  <%= link_to "Edit Book", edit_book_path(@book.id), class: "button" %>
  <%= link_to "Delete Book", book_path(@book.id), class: "button", method: :delete, data: { confirm: "Are you sure?" } %>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bestread</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <header>
        <div class="container"><!-- begin header -->
        <%= link_to (image_tag "http://www.waes.info/logo.png"), root_path %>

  <!--Nav bar  -->
        <nav>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "MyBestRead", mybestread_path %></li>
          <li><%= link_to "All Authors", "/authors" %></li>
          <li><%= link_to "All Books", "/books" %></li>
          <li><%= link_to "Logout", root_path %></li>
        </nav>
      </div>

      </header>
  <!-- end header  -->

<div class="container"><%= yield %>
  </div>    </body>
  </html>

app/views/mybestread/profile.html.erb
<div class="container"><h1>Welcome to My Best Read</h1>
  <h2>Your private profile on Best Read</h2>

  <article><h3>The last four books you've read</h3>
    <div>
      <ul>
      <% @readbooks.each do |readbook| %>
      <li><%= image_tag readbook.cover_img, size: "90x134"%>
        <div>
          <%= readbook.author.full_name %>
          <%= readbook.year %></li>
        </div>
      <% end %>
      </ul>
    </div>

    <div>
      <p>Read a new book? Add it here! </p><%= link_to "[Add New Book]", new_book_path %>

      <hr>

      <h3>Books on your wishlist</h3>
      <ul>
      <% @wishbooks.each do |wishbook| %>
      <li><%= image_tag wishbook.cover_img, size: "90x134"%>
        <div>
          <%= wishbook.author.full_name %>
          <%= wishbook.year %>
        </div></li>
      <% end %>
      </ul>
    </div>
    </article>
  </div>

app/views/pages/home.html.erb
<h1>Welcome to BestRead</h1>
<h2>Your online Book Club</h2>

<p></p>


<div class="book">
  <%= link_to (image_tag @last_book.cover_img, size: "360x536"), book_path(@last_book.id) %>
  <p><%= link_to "See a list of all books", books_path %></p>
</div>
<div class="author">
  <%= link_to (image_tag @last_author.author_img, size: "360x536"), author_path(@last_author.id) %>
  <p><%= link_to "See a list of all books", authors_path %></p>
</div>